"""Train a synthetic-only triage classifier with IndicBERT.

This creates a demonstration model for the hackathon prototype. The generated data
is synthetic and must NOT be presented as clinically validated evidence.
"""
import csv
import os
import subprocess
from pathlib import Path

from datasets import Dataset
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split
from transformers import AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments

MODEL = "ai4bharat/indic-bert"
LABELS = ["LEVEL_1_EMERGENCY", "LEVEL_2_URGENT", "LEVEL_3_PRIMARY_CARE", "LEVEL_4_ROUTINE"]
ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "synthetic_triage_generated.csv"
OUT = ROOT / "models" / "triage-synthetic"

if not DATA.exists():
    subprocess.run(["python", str(ROOT / "scripts" / "generate_synthetic_data.py")], check=True)

with DATA.open(encoding="utf-8") as f:
    rows = list(csv.DictReader(f))

train_rows, test_rows = train_test_split(
    rows, test_size=0.2, random_state=42, stratify=[r["label"] for r in rows]
)

def make_dataset(items):
    return Dataset.from_list([{**r, "labels": LABELS.index(r["label"])} for r in items])

tokenizer = AutoTokenizer.from_pretrained(MODEL, token=os.getenv("HF_TOKEN"))

def encode(batch):
    return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

train_ds = make_dataset(train_rows).map(encode, batched=True)
test_ds = make_dataset(test_rows).map(encode, batched=True)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL, num_labels=len(LABELS), token=os.getenv("HF_TOKEN"), ignore_mismatched_sizes=True
)

args = TrainingArguments(
    output_dir=str(OUT),
    num_train_epochs=float(os.getenv("TRIAGE_EPOCHS", "3")),
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    report_to="none",
)

def metrics(eval_pred):
    logits, labels = eval_pred
    preds = logits.argmax(axis=-1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1_macro": f1_score(labels, preds, average="macro"),
    }

trainer = Trainer(model=model, args=args, train_dataset=train_ds, eval_dataset=test_ds, compute_metrics=metrics)
trainer.train()
results = trainer.evaluate()
trainer.save_model(str(OUT))
tokenizer.save_pretrained(str(OUT))

(OUT / "TRAINING_NOTICE.txt").write_text(
    "Synthetic demonstration model only. Training data is generated by scripts/generate_synthetic_data.py. "
    "Metrics are not clinical validation and must not be used to claim medical performance.\n",
    encoding="utf-8",
)
print("Saved:", OUT)
print("Evaluation:", results)
